-- NovrSOC — Supabase case management + SOAR engine schema (replaces TheHive).
--
-- Run this whole file once in the Supabase SQL editor. It is safe to re-run.
--
-- Differences from the SQL in the "Full SOAR Rebuild" spec, and why:
--
-- 1. `public.playbooks` ALREADY EXISTS (columns: id, name, icon, severity, description,
--    estimated_time, steps jsonb, org_id, created_by, created_at, updated_at — confirmed live).
--    The spec's `CREATE TABLE IF NOT EXISTS playbooks` would therefore be skipped, and its seed
--    INSERT names columns that table does not have (trigger_technique, trigger_severity,
--    step_ids). That INSERT errors, and because the SQL editor runs a script as one
--    transaction, the error rolls back every table above it too — nothing would be created.
--    Here the three columns are ADDED to the existing table instead, and the seed updates the
--    matching existing playbooks rather than inserting duplicates of them.
--
-- 2. case_number is generated by the database from case_number_seq. The spec created that
--    sequence but never used it; both writers computed "latest number + 1" client-side, which
--    races: Wazuh runs the integration once per alert, so two alerts a millisecond apart get
--    the same number, and the UNIQUE constraint rejects the second case outright. The writers
--    still send nothing for case_number and let this default fill it.
--
-- 3. The service-role policies are created only if missing, so re-running doesn't fail on
--    "policy already exists".

-- ── Cases ─────────────────────────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS case_number_seq START 1;

CREATE TABLE IF NOT EXISTS public.cases (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number       TEXT UNIQUE NOT NULL DEFAULT ('CASE-' || lpad(nextval('case_number_seq')::text, 4, '0')),
  org_id            TEXT NOT NULL DEFAULT 'cybernovr',
  title             TEXT NOT NULL,
  description       TEXT,
  severity          TEXT NOT NULL DEFAULT 'medium',
  status            TEXT NOT NULL DEFAULT 'open',
  source            TEXT NOT NULL DEFAULT 'wazuh',
  source_id         TEXT,
  agent_id          TEXT,
  agent_name        TEXT,
  source_ip         TEXT,
  dest_ip           TEXT,
  rule_id           TEXT,
  rule_level        INTEGER DEFAULT 0,
  mitre_technique   TEXT,
  mitre_tactic      TEXT,
  assigned_to       TEXT,
  playbook_id       UUID,
  tags              TEXT[] DEFAULT '{}',
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW(),
  resolved_at       TIMESTAMPTZ,
  auto_closed       BOOLEAN DEFAULT false,
  tier              INTEGER DEFAULT 1,
  containment_done  BOOLEAN DEFAULT false,
  escalated         BOOLEAN DEFAULT false,
  UNIQUE(source, source_id)
);

-- If an earlier run of the spec's SQL created the table without the default, add it now.
ALTER TABLE public.cases
  ALTER COLUMN case_number SET DEFAULT ('CASE-' || lpad(nextval('case_number_seq')::text, 4, '0'));

CREATE INDEX IF NOT EXISTS cases_org_created_idx ON public.cases (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS cases_org_status_idx  ON public.cases (org_id, status);
CREATE INDEX IF NOT EXISTS cases_org_tier_idx    ON public.cases (org_id, tier);

CREATE TABLE IF NOT EXISTS public.case_notes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id    UUID REFERENCES public.cases(id) ON DELETE CASCADE,
  author     TEXT NOT NULL,
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.case_tasks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id     UUID REFERENCES public.cases(id) ON DELETE CASCADE,
  step_id     TEXT NOT NULL,
  title       TEXT NOT NULL,
  description TEXT,
  status      TEXT DEFAULT 'pending',
  automated   BOOLEAN DEFAULT false,
  result      TEXT,
  executed_at TIMESTAMPTZ,
  executed_by TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.case_timeline (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id    UUID REFERENCES public.cases(id) ON DELETE CASCADE,
  actor      TEXT NOT NULL,
  action     TEXT NOT NULL,
  details    TEXT,
  automated  BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.case_iocs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id     UUID REFERENCES public.cases(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  value       TEXT NOT NULL,
  verdict     TEXT,
  risk_score  INTEGER DEFAULT 0,
  enriched_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS case_notes_case_idx    ON public.case_notes (case_id);
CREATE INDEX IF NOT EXISTS case_tasks_case_idx    ON public.case_tasks (case_id);
CREATE INDEX IF NOT EXISTS case_timeline_case_idx ON public.case_timeline (case_id);
CREATE INDEX IF NOT EXISTS case_iocs_case_idx     ON public.case_iocs (case_id);

-- ── Playbook steps + playbook triggers ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.playbook_steps (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  step_id     TEXT UNIQUE NOT NULL,
  name        TEXT NOT NULL,
  description TEXT,
  category    TEXT NOT NULL,
  automated   BOOLEAN DEFAULT true,
  script_name TEXT NOT NULL,
  params      JSONB DEFAULT '{}',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Existing table — extend it rather than recreate it (see note 1 above).
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS trigger_technique TEXT;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS trigger_severity  TEXT;
ALTER TABLE public.playbooks ADD COLUMN IF NOT EXISTS step_ids          TEXT[] DEFAULT '{}';

-- ── SOAR automation log ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.soar_log (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id      UUID REFERENCES public.cases(id) ON DELETE SET NULL,
  tier         INTEGER NOT NULL,
  action       TEXT NOT NULL,
  result       TEXT,
  automated    BOOLEAN DEFAULT true,
  executed_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS soar_log_case_idx     ON public.soar_log (case_id);
CREATE INDEX IF NOT EXISTS soar_log_executed_idx ON public.soar_log (executed_at DESC);

-- ── RLS: service role only ────────────────────────────────────────────────────────────────
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['cases','case_notes','case_tasks','case_timeline','case_iocs','playbook_steps','playbooks','soar_log'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = t AND policyname = t || '_service'
    ) THEN
      EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL USING (auth.role() = ''service_role'')', t || '_service', t);
    END IF;
  END LOOP;
END $$;

-- ── Seed: pre-built steps ─────────────────────────────────────────────────────────────────
INSERT INTO public.playbook_steps (step_id, name, description, category, automated, script_name) VALUES
  ('block_ip',        'Block Source IP',              'Block source IP at OPNsense firewall',           'containment',    true,  'block_ip.py'),
  ('enrich_iocs',     'Enrich IOCs',                  'Enrich all IOCs across 9 CTI sources',           'investigation',  true,  'enrich_iocs.py'),
  ('isolate_agent',   'Isolate Wazuh Agent',          'Run active response to isolate endpoint',        'containment',    true,  'isolate_agent.py'),
  ('notify_email',    'Send Email Notification',      'Email the SOC team mailbox',                     'notification',   true,  'notify_email.py'),
  ('notify_ciso',     'Email CISO',                   'Send escalation email to CISO',                  'escalation',     true,  'notify_ciso.py'),
  ('get_processes',   'Snapshot Running Processes',   'Get list of running processes on endpoint',      'investigation',  true,  'get_processes.py'),
  ('search_related',  'Search Related Alerts',        'Find related alerts from same IP/technique',     'investigation',  true,  'search_related.py'),
  ('generate_report', 'Generate Incident Report',     'Generate full incident report as markdown',      'reporting',      true,  'generate_report.py'),
  ('check_asset',     'Check Asset Details',          'Look up affected asset in Supabase',             'investigation',  true,  'check_asset.py'),
  ('geo_enrich',      'Geolocate Source IP',          'Get country and Nigerian state for source IP',   'investigation',  true,  'geo_enrich.py')
ON CONFLICT (step_id) DO NOTHING;

-- ── Seed: playbook triggers ───────────────────────────────────────────────────────────────
-- Existing playbooks that cover the same ground get triggers attached instead of a duplicate
-- row. The spec's "Phishing Response" maps onto the existing "Phishing Investigation".
UPDATE public.playbooks SET trigger_technique = 'T1110', trigger_severity = 'high',
  step_ids = ARRAY['block_ip','enrich_iocs','search_related','notify_email','generate_report']
  WHERE org_id = 'cybernovr' AND name = 'Brute Force Response';
UPDATE public.playbooks SET trigger_technique = 'T1486', trigger_severity = 'critical',
  step_ids = ARRAY['isolate_agent','block_ip','notify_ciso','get_processes','generate_report']
  WHERE org_id = 'cybernovr' AND name = 'Ransomware Response';
UPDATE public.playbooks SET trigger_technique = 'T1566', trigger_severity = 'high',
  step_ids = ARRAY['enrich_iocs','block_ip','notify_email','generate_report']
  WHERE org_id = 'cybernovr' AND name = 'Phishing Investigation';

-- The three with no existing equivalent. `steps` is filled so the Playbooks page and the
-- case "Attach Playbook" picker (which read `steps`) show real steps rather than an empty list.
INSERT INTO public.playbooks (org_id, name, icon, severity, description, estimated_time, steps, trigger_technique, trigger_severity, step_ids, created_by)
SELECT v.org_id, v.name, v.icon, v.severity, v.description, v.estimated_time, v.steps::jsonb, v.trigger_technique, v.trigger_severity, v.step_ids, 'system'
FROM (VALUES
  ('cybernovr', 'Lateral Movement', '🔀', 'critical', 'Respond to lateral movement', '2-4 hours',
   '[{"order":1,"phase":"Containment","title":"Isolate Wazuh Agent","est_mins":0,"description":"Run active response to isolate endpoint"},{"order":2,"phase":"Containment","title":"Block Source IP","est_mins":0,"description":"Block source IP at OPNsense firewall"},{"order":3,"phase":"Investigation","title":"Snapshot Running Processes","est_mins":0,"description":"Get list of running processes on endpoint"},{"order":4,"phase":"Escalation","title":"Email CISO","est_mins":0,"description":"Send escalation email to CISO"},{"order":5,"phase":"Reporting","title":"Generate Incident Report","est_mins":0,"description":"Generate full incident report as markdown"}]',
   'T1021', 'critical', ARRAY['isolate_agent','block_ip','get_processes','notify_ciso','generate_report']),
  ('cybernovr', 'Generic High Severity', '🟠', 'high', 'Default response for high severity', '1-2 hours',
   '[{"order":1,"phase":"Investigation","title":"Enrich IOCs","est_mins":0,"description":"Enrich all IOCs across CTI sources"},{"order":2,"phase":"Investigation","title":"Search Related Alerts","est_mins":0,"description":"Find related alerts from same IP/technique"},{"order":3,"phase":"Notification","title":"Send Email Notification","est_mins":0,"description":"Email the SOC team mailbox"},{"order":4,"phase":"Reporting","title":"Generate Incident Report","est_mins":0,"description":"Generate full incident report as markdown"}]',
   NULL, 'high', ARRAY['enrich_iocs','search_related','notify_email','generate_report']),
  ('cybernovr', 'Generic Critical', '🔴', 'critical', 'Default response for critical severity', '1-4 hours',
   '[{"order":1,"phase":"Containment","title":"Block Source IP","est_mins":0,"description":"Block source IP at OPNsense firewall"},{"order":2,"phase":"Investigation","title":"Enrich IOCs","est_mins":0,"description":"Enrich all IOCs across CTI sources"},{"order":3,"phase":"Escalation","title":"Email CISO","est_mins":0,"description":"Send escalation email to CISO"},{"order":4,"phase":"Reporting","title":"Generate Incident Report","est_mins":0,"description":"Generate full incident report as markdown"}]',
   NULL, 'critical', ARRAY['block_ip','enrich_iocs','notify_ciso','generate_report'])
) AS v(org_id, name, icon, severity, description, estimated_time, steps, trigger_technique, trigger_severity, step_ids)
WHERE NOT EXISTS (SELECT 1 FROM public.playbooks p WHERE p.org_id = v.org_id AND p.name = v.name);
